import esbuild from "esbuild";
import process from "process";
import esbuildSvelte from "esbuild-svelte";
import sveltePreprocess from "svelte-preprocess";
import { builtinModules as builtins } from "node:module";
import { execSync } from "child_process";
import chokidar from "chokidar";
import path from "path";
import fs, { mkdirSync } from "fs";

const banner = `/*!
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin

Knap for Obsidian
Copyright (c) 2026 Pantalytics
Copyright (c) 2024-2026 Entire VC
Copyright (c) 2024 No Instructions, LLC

MIT licensed. Forked from EVC Team Relay, which derives from Relay by
No Instructions, LLC.

This bundle includes third-party code under the MIT, ISC, BSD-3-Clause,
0BSD and Apache-2.0 licences. Attribution for every bundled component,
and for the source vendored into this repository, is in the NOTICE file
that ships beside this one and in the repository's NOTICE.
*/
`;

// The version this build reports about itself: the Relay-Version header,
// the health check's ?version=, the device row on Knap's page, and the pill
// the settings screen shows when it differs from the manifest. In CI the
// checkout is shallow and the release tag does not exist yet, so `git
// describe` degrades to a bare commit SHA; every shipped build then reported
// a SHA, the pill showed on all of them, and a signal that should mean
// "this build is not the release" meant nothing. A describe that carries no
// tag falls back to the manifest's version, which is what the release is
// about to be named.
//
// The directory's build verification is the second thing this has to survive.
// It unpacks the release's source and runs `npm run build` with no `.git`
// beside it, so an unguarded `git describe` throws EEXIT and the whole build
// fails before esbuild starts. That is what the 1.13.6 scorecard reported as
// "Build verification failed while running the build script". No git, no
// describe, no problem: fall back to the manifest, which is the version the
// release is named after anyway.
const manifestVersion = JSON.parse(
	fs.readFileSync("manifest.json", "utf8"),
).version;
let described = "";
try {
	described = execSync("git describe --tags --always", {
		encoding: "utf8",
		stdio: ["ignore", "pipe", "ignore"],
	}).trim();
} catch {
	described = "";
}
const gitTag =
	described === "" || /^[0-9a-f]{7,40}$/.test(described)
		? manifestVersion
		: described;

const develop = process.argv[2] === "develop";
const staging = process.argv[2] === "staging";
const watch = process.argv[2] === "watch" || staging;
const debug = process.argv[2] === "debug" || watch || staging || develop;
const out = process.argv[3] || ".";
const tld = staging ? "dev" : "md";

// Obsidian vault plugin directory for auto-copy on build
// Where a dev build gets copied. No default vault path: upstream hardcoded
// one developer's own vault here, which silently does nothing for everybody
// else. Set OBSIDIAN_PLUGIN_DIR to enable the copy.
const obsidianPluginDir = process.env.OBSIDIAN_PLUGIN_DIR || "";

// Knap uses relay-onprem mode, no default System 3 URLs.
const apiUrl = "";
const authUrl = "";

// The one Knap server (ADR-0033), and therefore one address. There is no
// server field and no second server, so it is build configuration rather than
// user input, and it lives here rather than in a source file that ships.
//
// It was three addresses, and that is what broke. The server moved to the app
// host on 13 August 2026, where Caddy serves exactly one name; the control
// plane kept pointing at cp.knap.pantalytics.com, which from then on answered
// every TLS handshake with an internal error. The health poll asked it every
// ten seconds, failed, and put "You're offline" over a vault that was
// syncing perfectly well. Deriving the other two from the address the client
// actually syncs with is what stops that returning, rather than repairing it
// once.
//
// KNAP_SERVER_URL doubles as the rebuild's beta switch below, so it stays
// empty in an ordinary build. The fallback here is the address a release
// carries. The bare domain is the marketing site on another box, so it is
// app.knap.pantalytics.com and not knap.pantalytics.com.
const knapUrl = process.env.KNAP_SERVER_URL || "https://app.knap.pantalytics.com";
const controlPlaneUrl = process.env.KNAP_CONTROL_PLANE_URL || knapUrl;
const panelUrl = process.env.KNAP_PANEL_URL || `${knapUrl}/sync`;
console.log("knap:", knapUrl);
console.log("git tag:", gitTag);

// Desktop notification on a failed watch build. notify-send does not exist on
// CI or on the directory's verifier, where a failing build would otherwise
// fail twice and report the wrong reason, so the notification is best effort.
const NotifyPlugin = {
	name: "on-end",
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length === 0) return;
			try {
				execSync(`notify-send "Build Failed"`, { stdio: "ignore" });
			} catch {
				// no notification daemon here; the esbuild error is the signal
			}
		});
	},
};

const YjsInternalsPlugin = {
	name: "yjs-internals",
	setup(build) {
		build.onResolve({ filter: /^yjs\/dist\/src\/internals$/ }, args => {
			return {
				path: path.resolve("node_modules/yjs/src/internals.js"),
			};
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
        "moment",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	plugins: [
		esbuildSvelte({
			// Svelte 5 dropped the boolean form: true became "injected".
			compilerOptions: { css: "injected" },
			preprocess: sveltePreprocess(),
		}),
		YjsInternalsPlugin,
		NotifyPlugin,
	],
	target: "es2018",
	minify: !debug,
	logLevel: "info",
	sourcemap: debug ? "inline" : false,
	define: {
		BUILD_TYPE: debug ? '"debug"' : '"prod"',
		GIT_TAG: `"${gitTag}"`,
		API_URL: `"${apiUrl}"`,
		AUTH_URL: `"${authUrl}"`,
		CONTROL_PLANE_URL: JSON.stringify(controlPlaneUrl),
		PANEL_URL: JSON.stringify(panelUrl),
		// The address src/knap/ObsidianKnap.ts registers against. It used to
		// default to empty, so `npm run build` produced a plugin with the whole
		// rebuild path switched off while the release, built with the repository
		// variable set, shipped it on. The directory rebuilds a release from its
		// source with no repository variables, so those two builds could never
		// match and build verification had nothing to verify. It defaults to the
		// same one server as everything else here (ADR-0033); the environment
		// still overrides it to point a test build somewhere else.
		KNAP_SERVER_URL: JSON.stringify(knapUrl),
		REPOSITORY: `"pantalytics/knap-obsidian"`,
	},
	treeShaking: true,
	loader: {
		".png": "dataurl",
	},
	outfile: out + "/main.js",
});

const copyFile = (src, dest) => {
	if (src === dest) {
		return;
	}
	fs.copyFileSync(src, dest);
	console.log(`Copied ${src} to ${dest}`);
};

const watchAndMove = (fnames, mapping) => {
	// only usable on top level directory
	const watcher = chokidar.watch(fnames, {
		ignored: /(^|[/\\])\../, // ignore dotfiles
		persistent: true,
	});

	watcher.on("change", (filePath) => {
		const destName = mapping[filePath] || filePath;
		const destPath = path.join(out, path.basename(destName));
		copyFile(filePath, destPath);
	});
};

const mapping = debug ? { "manifest-beta.json": "manifest.json" } : {};
const manifest = debug ? "manifest-beta.json" : "manifest.json";
const files = ["styles.css", manifest];

const updateManifest = (manifest) => {
	const manifestPath = path.join(out, path.basename("manifest.json"));

	// Only ever stamp a copy. When `out` is the repo root the join resolves
	// back to the source manifest, and a plain `npm run build` would rewrite
	// its version to the git describe string and reindent it. That is how a
	// developer who builds and then commits trips manifest-check, which is
	// the one CI job that actually blocks.
	if (path.resolve(manifestPath) === path.resolve("manifest.json")) {
		console.log("Skipping version stamp: output is the source tree");
		return;
	}

	const raw_manifest = fs.readFileSync(manifestPath);
	const parsed = JSON.parse(raw_manifest);
	parsed.version = gitTag;
	const new_manifest = JSON.stringify(parsed, null, 2);
	console.log(`Set ${manifest} version to ${gitTag}`);
	fs.writeFileSync(manifestPath, new_manifest);
};

const move = (fnames, mapping) => {
	// only usable on top level directory
	mkdirSync(out, { recursive: true });
	for (const fname of fnames) {
		const destName = mapping[fname] || fname;
		const destPath = path.join(out, path.basename(destName));
		copyFile(fname, destPath);
	}
};

// Copy build output to Obsidian plugin directory
const copyToObsidian = () => {
	if (!obsidianPluginDir) {
		return;
	}
	if (!fs.existsSync(obsidianPluginDir)) {
		console.log(`Obsidian plugin dir not found: ${obsidianPluginDir}`);
		return;
	}
	const filesToCopy = ["main.js", "manifest.json", "styles.css"];
	for (const fname of filesToCopy) {
		const src = path.join(out, fname);
		const dest = path.join(obsidianPluginDir, fname);
		if (fs.existsSync(src)) {
			copyFile(src, dest);
		}
	}
	console.log(`Copied to Obsidian: ${obsidianPluginDir}`);
};

if (watch) {
	await context.watch();
	move(files, mapping);
	if (!develop) {
		updateManifest();
	}
	copyToObsidian();
	watchAndMove(files, mapping);
} else {
	await context.rebuild();
	move(files, mapping);
	if (!develop) {
		updateManifest();
	}
	copyToObsidian();
	process.exit(0);
}
